apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: mynginx
  namespace: kubebb-system
spec:
  approved: true
  name: nginx
  version: 15.1.2
  component:
    name: repository-chartmuseum.nginx
    namespace: kubebb-system
