apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Repository
metadata:
  name: repository-grafana-sample
  namespace: kubebb-system
spec:
  url: https://grafana.github.io/helm-charts
  pullStategy:
    intervalSeconds: 120
    retry: 5
